### ISSUE TITLE
Index properly in clearErrors

### ISSUE THREAD

**Issue by vidartf** [KhronosGroup/WebGLDeveloperTools#4]
I assume [this line](https://github.com/KhronosGroup/WebGLDeveloperTools/blob/80658b130e5da8eca9f0f5c08a6d65d5caecaffd/src/debug/webgl-debug.js#L624) needs indexing:
```diff
for (var ii = 0; ii < k.length; ++ii) {
-    delete glErrorShadow_[k];
+    delete glErrorShadow_[k[ii]];
}
```

**Comment by zhenyao** [comment]
Right.  Thanks for catching this.  Can you upload a pull request to fix it?

**Comment by vidartf** [comment]
Submitted in #5. Just wasn't sure if this was the right place to submit it, since the major commit says this is a copy of content from another repository.

**Comment by zhenyao** [comment]
@kenrussell Do you know if we can directly modify this or we need to update an upstream repo?

**Comment by kenrussell** [comment]
Sorry for the delay replying. This repository can be updated directly. It's pulled in to KhronosGroup/WebGL as a git submodule.
